import type { Metadata } from "next";
import "./globals.css";
import BitsolLogo from '../public/Logo-White-Large.png'
import Image from "next/image";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
 
      
      {children}
      
      </body>
    </html>
  );
}
